{
    0: Country("Czechia"),
    1: Country("Greece"),
    2: Country("France"),
    3: Country("Estonia"),
    4: Country("Italy"),
    5: Country("Austria"),
    6: Country("Moldova"),
    7: Country("Portugal"),
    8: Country("Finland"),
    9: Country("Norway"),
    10: Country("Slovakia"),
    11: Country("Ireland"),
    12: Country("Kosovo"),
    13: Country("Denmark"),
    14: Country("Germany"),
    15: Country("Montenegro"),
    16: Country("Romania"),
    17: Country("Lithuania"),
    18: Country("Bulgaria"),
    19: Country("Hungary"),
    20: Country("Belgium"),
    21: Country("Bosnia and Herzegovina"),
    22: Country("Spain"),
    23: Country("Croatia"),
    24: Country("Switzerland"),
    25: Country("Slovenia"),
    26: Country("Poland"),
    27: Country("Serbia"),
    28: Country("Netherlands"),
    29: Country("Ukraine"),
    30: Country("Latvia"),
    31: Country("United Kingdom"),
    32: Country("Sweden"),
    33: Country("Macedonia"),
    34: Country("Albania"),
}
